### ISSUE TITLE
JS errors on zero config

### ISSUE THREAD

**Issue by LipGlossary** [zolk/docsify-theme-switcher#7]
If you want to support these degenerate cases...

When `window.$docsify.themeSelector` is left undefined:
```
Uncaught TypeError: Cannot destructure property 'themes' of 'window.$docsify.themeSelector' as it is undefined.
    at theme-switcher.min.js:1:18
    at theme-switcher.min.js:1:1113
```

When `window.$docsify.themeSelector.themes` is empty (`[]`)—`undefined` only results in the second error:
```
Docsify plugin error TypeError: Cannot read properties of undefined (reading 'class')
    at i (functions.js:41:64)
    at theme-switcher.js:21:35
    at u (docsify@4:1:160423)
    at u (docsify@4:1:160445)
    at n.callHook (docsify@4:1:160515)
    at new n (docsify@4:1:148066)
    at HTMLDocument.<anonymous> (docsify@4:1:160744)
```
```
docsify@4:1 Docsify plugin error TypeError: Cannot read properties of null (reading 'style')
    at o (functions.js:54:6)
    at theme-switcher.js:34:5
    at u (docsify@4:1:160423)
    at docsify@4:1:160350
    at custom-replacements.js:90:5
    at u (docsify@4:1:160330)
    at n.callHook (docsify@4:1:160515)
    at n._renderMain (docsify@4:1:154264)
    at c (docsify@4:1:149034)
    at XMLHttpRequest.<anonymous> (docsify@4:1:7606)
```

Minimum viable config:
```
window.$docsify = {
  // ...normal config
  themeSelector: { themes: [{}] },
};
```

`themeSelector: { pathRegex: /never-gonna-match/ }` does not prevent the error `at o (functions.js:54:6)`.

**Comment by zolk** [comment]
🙇 Thank you, I will plan on more gracefully handling these scenarios.
